In [1]:
import tensorflow as tf


In [2]:
n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons],dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons,n_neurons],dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

init = tf.global_variables_initializer()

In [3]:
import numpy as np

# Mini-batch:        instance 0,instance 1,instance 2,instance 3
X0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]]) # t = 0
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]]) # t = 1

with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})

In [5]:
print(Y0_val)
print(Y0)

[[ 0.9958393  -0.92505336  0.99997282 -0.98942125 -0.45412788]
 [ 1.         -0.99930739  1.         -1.         -0.99895984]
 [ 1.         -0.99999398  1.         -1.         -0.99999851]
 [ 1.          0.96784598 -0.99999952 -1.         -0.99999881]]
Tensor("Tanh:0", shape=(?, 5), dtype=float32)


In [6]:
print(Y1_val)

[[ 1.         -1.         -1.          1.         -0.9933725 ]
 [ 0.8592366   0.89917558  0.52930582  0.97723347  0.92241365]
 [ 0.99999851 -1.         -0.99999905  1.          0.31175208]
 [ 0.92692316 -0.99798769 -0.99987853  0.99999988  0.98958308]]


In [1]:
import tensorflow as tf
n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(
                          basic_cell, [X0, X1], dtype=tf.float32)
Y0, Y1 = output_seqs

In [1]:
import tensorflow as tf
import numpy as np

n_inputs = 3
n_neurons = 5
n_steps = 2

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)


In [2]:
init = tf.global_variables_initializer()

In [4]:
seq_length = tf.placeholder(tf.int32, [None])

In [5]:
X_batch = np.array([
        # step 0     step 1
        [[0, 1, 2], [9, 8, 7]], # instance 0
        [[3, 4, 5], [0, 0, 0]], # instance 1 (padded with a zero vector)
        [[6, 7, 8], [6, 5, 4]], # instance 2
        [[9, 0, 1], [3, 2, 1]], # instance 3
    ])
seq_length_batch = np.array([2, 1, 2, 2])

In [6]:
with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run(
        [outputs, states], feed_dict={X: X_batch, seq_length: seq_length_batch})

In [7]:
print(outputs_val)

[[[ 0.91348475 -0.6488589  -0.72141463 -0.88729715  0.33300832]
  [ 1.          0.68695682 -0.99053389 -1.          0.9993391 ]]

 [[ 0.99998027 -0.75490028 -0.98083276 -0.99998957  0.96258676]
  [ 0.85695493  0.61309147  0.72311914 -0.37197191 -0.41239905]]

 [[ 1.         -0.83217746 -0.99884343 -1.          0.99854845]
  [ 0.99999988  0.78921843 -0.73006541 -1.          0.98571217]]

 [[ 0.99991429  0.99993956 -0.98881102 -0.99990582  0.99917835]
  [ 0.99912536  0.83210337 -0.58819336 -0.99731255  0.91814846]]]


In [8]:
print(states_val)


[[ 1.          0.68695682 -0.99053389 -1.          0.9993391 ]
 [ 0.85695493  0.61309147  0.72311914 -0.37197191 -0.41239905]
 [ 0.99999988  0.78921843 -0.73006541 -1.          0.98571217]
 [ 0.99912536  0.83210337 -0.58819336 -0.99731255  0.91814846]]
